
[mongo]
uri = "mongodb+srv://preritmehta77_db_user:mIP0oKJsTMEeIm5p@cluster1.iuexd8p.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"
GOOGLE_API_KEY=AIzaSyCwdTJtuHhD49OeKrsNZVz0OSKGlbRCLi8
GEMINI_MODEL=gemini-2.5-flash